# Generated by Django 5.1.1 on 2024-10-31 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=255)),
                ('penyelenggara', models.CharField(max_length=255)),
                ('durasi', models.CharField(max_length=64)),
                ('kuota', models.PositiveIntegerField()),
                ('deskripsi', models.TextField()),
                ('rincian_kegiatan', models.TextField()),
                ('kriteria_peserta', models.TextField()),
                ('sks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Konversi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_konversi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sedang_diverifikasi', 'Sedang Diverifikasi'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], max_length=20)),
                ('matkul_konversi', models.CharField(max_length=255)),
                ('ipk', models.FloatField()),
                ('document', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('universitas', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=50)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
