# Generated by Django 5.1.1 on 2024-11-01 01:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0002_alter_konversi_document_alter_konversi_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Mahasiswa',
        ),
    ]
