# Generated by Django 5.1.1 on 2024-11-01 02:11

import django.db.models.deletion
import mbkmapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0003_rename_userprofile_mahasiswa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konversi',
            name='user',
        ),
        migrations.AddField(
            model_name='konversi',
            name='mahasiswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mbkmapp.mahasiswa'),
        ),
        migrations.AlterField(
            model_name='konversi',
            name='ipk',
            field=models.FloatField(validators=[mbkmapp.models.validate_ipk]),
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='konversi',
            name='dosen_wali',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konversi_mahasiswa', to='mbkmapp.dosen'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='dosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa', to='mbkmapp.dosen'),
        ),
        migrations.CreateModel(
            name='Verifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_verifikasi', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sedang_diverifikasi', 'Sedang Diverifikasi'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('dosen_wali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen_verifikasi', to='mbkmapp.dosen')),
            ],
        ),
        migrations.AddField(
            model_name='konversi',
            name='verifikasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konversi', to='mbkmapp.verifikasi'),
        ),
    ]
