# Generated by Django 5.1.1 on 2024-11-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0004_remove_konversi_user_konversi_mahasiswa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konversi',
            name='id_konversi',
        ),
    ]
