# Generated by Django 5.1.1 on 2024-11-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0005_remove_konversi_id_konversi'),
    ]

    operations = [
        migrations.AddField(
            model_name='konversi',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konversi_program', to='mbkmapp.program'),
        ),
    ]
